version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    # volumes:
    #   - ./data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
